# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
Party.create(name: 'A la bourse', thema: "Capitalist",description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Optio, minima sequi obcaecati quo temporibus blanditiis, cum et minus corrupti consectetur tempora eum inventore vitae laborum illum quisquam eos vel totam!", guest_min:"5",guest_max:"15",price_per_person:"10",total_price:"50", date:"28.12.2015", starting_hour:"14.37", ending_hour:"15.37", city:"Bruxelles", zip_code:"1040", street:"Rue Charles Degroux", number:"78" )
Party.create(name: 'A la bastille', thema: "Folie bourgoise",description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Esse possimus vel numquam adipisci, distinctio perspiciatis veniam explicabo id illum laborum. Consequatur nisi repellat aperiam, pariatur consectetur expedita ut laboriosam sunt!", guest_min:"5",guest_max:"15",price_per_person:"10",total_price:"50", date:"28.12.2015", starting_hour:"14.37", ending_hour:"15.37", city:"Bruxelles", zip_code:"1040", street:"Rue Charles Degroux", number:"78" )
Party.create(name: 'Chez Jawad', thema: "collocataire ",description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Voluptate vero odio beatae atque quas natus dignissimos voluptatibus placeat, amet ipsa, modi dolores doloremque esse eveniet! Doloribus iure at minima commodi.", guest_min:"5",guest_max:"15",price_per_person:"10",total_price:"50", date:"28.12.2015", starting_hour:"14.37", ending_hour:"15.37", city:"Bruxelles", zip_code:"1040", street:"Rue Charles Degroux", number:"78"  )
Party.create(name: 'Pizza and Fifa', thema: "entertainment",description:"Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quos ducimus aliquid magnam, cupiditate quae maiores velit voluptas architecto libero neque, voluptates at, dolore! Ducimus placeat, dolorem cum temporibus molestiae officiis!",guest_min:"5",guest_max:"15",price_per_person:"10",total_price:"50", date:"28.12.2015", starting_hour:"14.37", ending_hour:"15.37", city:"Bruxelles", zip_code:"1040", street:"Rue Charles Degroux", number:"78"  )
